### ISSUE TITLE
High CPU after a few minutes.

### ISSUE THREAD

**Issue by foufee** [shauleiz/SmartPropoPlus#3]
Using a USB audio adapter, the CPU usage of SPP spikes to about 30% on an i7 after a few minutes, this is causing significant FPS drop in the game. Restarting SPP clears it for a few minutes.

**Comment by shauleiz** [comment]
It is impossible to guess why this happens.
I can only attempt some guesses:

- On a lightly loaded CPU any process can reach 30% if it is the only serious application running.
- FPS is usually relate to load on graphic processor - not related to SSP.
- Did you test the memory consumption of the system?

**Comment by foufee** [comment]
It's stalling the event loop processing that is for certain (20+ years
senior dev here :-). Memory seems fine.  If it's easy enough to build,
since I can reproduce it very easily within a few minutes, I can
investigate.

It's not the only thing running, normally running FreeRider, LiftOff or
ClearViewRC.  SPP is hogging enough CPU to cause other processes to be
staved of CPU resources (not GPU). It makes the whole system perform pretty
shit (and the machine has 16Gb of ram, so chewing that much in 3 minutes
would be pretty impressive!).

Lets hope we can sort this out :-)

Cheers

Matthew

**Comment by shauleiz** [comment]
No offence intended, Matthew.
If you solve the problem, the code after all was developed on W7, I'll be glad to incorporate your fix.

**Comment by foufee** [comment]
None taken.

Unfortunately it was easier to fix some USB HID code on an Arduino to solve
the issue with LiftOff (it doesn't recognise the USB HID device of the 2
common PPM to HID projects for Arduino out there, but I've now solved that).

Therefore I no longer need to use SPP, until then, it was hugely helpful,
and saved me many hours of fixing RC planes....I thank you for your efforts!

Cheers

Matthew

**Comment by shauleiz** [comment]
No problem.
